name: Deployment
env:
  PUBLISH_DIR: bin/Release/net8.0/publish/wwwroot
  VERSION: 0.3.${{ github.run_number }}

# Controls when the action will run
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Publish application and capture warnings
        id: publish
        run: |
          dotnet publish -c Release -p:Version=${{ env.VERSION }} > build_output.txt 2>&1
          warnings=$(grep -c "warning" build_output.txt || true)
          echo "warnings=$warnings" >> $GITHUB_ENV
          if [ "$warnings" -gt 0 ]; then
            echo "Build failed due to warnings."
            cat build_output.txt
            exit 1
          fi
      
      # This step will only run if the previous step succeeded
      - name: Rewrite base href
        if: success()
        uses: SteveSandersonMS/ghaction-rewrite-base-href@v1
        with:
          html_path: ${{ env.PUBLISH_DIR }}/index.html
          base_href: https://mesmart34.github.io/phasma-buster/
      
      # Add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project (allow files and folders starting with an underscore)
      - name: Add .nojekyll file
        run: touch ${{ env.PUBLISH_DIR }}/.nojekyll

      - name: Commit to GitHub pages Repo
        if: success()
        uses: crazy-max/ghaction-github-pages@v1.5.1
        with:
          target_branch: gh-pages
          build_dir: ${{ env.PUBLISH_DIR }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # Optionally, display the number of warnings (runs even if previous steps fail)
      - name: Display number of warnings (if any)
        if: always()
        run: |
          echo "Number of warnings during build: ${{ env.warnings }}"
